### ISSUE TITLE
Inference on GPU

### ISSUE THREAD

**Issue by woreom** [matthew-pisano/bergeron#2]
Hi,

How should we do inference on GPU? Running `python evaluate.py ...` runs the model on the CPU.
I changed `interface.py` line 149 to f`p_kwargs = {'device_map':"auto"} `but I still get:

[ INFO accelerate.utils.modeling @ 15:02:09 ] Device 0 seems unavailable, Proceeding to check subsequent devices.
[ INFO accelerate.utils.modeling @ 15:02:09 ] Device 1 seems unavailable, Proceeding to check subsequent devices.

what should I do?

**Comment by matthew-pisano** [comment]
Hello,

Thank you for submitting an issue.  It looks like this originates within the `accelerate` library (see their [modeling.py](https://github.com/huggingface/accelerate/blob/13d93c4f505bca7a1075161d8246628e525958ad/src/accelerate/utils/modeling.py#L859) file).  It may be useful to check if CUDA is available at runtime (`torch.cuda.is_available()` or with [other useful checks](https://stackoverflow.com/questions/48152674/how-do-i-check-if-pytorch-is-using-the-gpu)).

Are you able to run other inference code (unrelated to this repository) without any similar errors?  Make sure any tests you perform also utilize `accelerate`.

On the surface, this appears to be a possible configuration error.  Let me know if you are able to narrow down the issue to this repository and I will take another look!

**Comment by woreom** [comment]
Hi,

I don't know what happened, but it seems to work now after I updated my Nvidia driver.
However, I'm getting this warning:

```
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
```
